RockyPoolServices/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from poolServices import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('review/', views.createReview, name='createReview'),
    path('services/', views.services_page, name = 'services'),
    path('reviews/', views.review_page, name = 'reviews'),
    path('clients/', include('clients.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    
   path('', views.new_client, name = 'clients'),
   path('repair_request', views.repair, name = 'repair'),
]

clients/models.py
from django.db import models

# Create your models here.
class repair_request(models.Model):
	name = models.CharField(max_length=100)
	number = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	message = models.TextField(max_length=500, blank=True)

	def __str__(self):
		return self.name

class new_client(models.Model):
	name = models.CharField(max_length=100)
	number = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	message = models.TextField(max_length=500, blank=True)


	def __str__(self):
		return self.name

poolServices/models.py
from django.db import models

class MonthlyService(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=500)
	image = models.ImageField(upload_to='poolServices/images/')

	def __str__(self):
		return self.title

class review(models.Model):
	name = models.CharField(max_length=50)
	location = models.CharField(max_length=50)
	comments = models.TextField(max_length=250, blank=True)
	

	def __str__(self):
		return self.name

clients/forms.py
from django.forms import ModelForm
from .models import *

class repair_form(ModelForm):
	class Meta:
		model = repair_request
		fields = ['name','number','email','message']

class client_form(ModelForm):
	class Meta:
		model = new_client
		fields = ['name','number','email','message']

poolServices/forms.py
from django.forms import ModelForm
from .models import review

class ReviewForm(ModelForm):
	class Meta:
		model = review
		fields = ['name','location','comments']

clients/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.
def repair(request):
	if request.method == "GET":
		return render(request,'clients/repair_form.html', {'form':repair_form()})
	else:
		form = repair_form(request.POST)
		repair_request = form.save()
		return redirect('home')


def new_client(request):
	if request.method == "GET":
		return render(request,'clients/new_client.html', {'form':client_form()})
	else:
		form = client_form(request.POST)
		client = form.save()
		return redirect('home')

poolServices/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import ReviewForm

def home(request):
	services = MonthlyService.objects.all()
	reviews = review.objects.order_by('-id')[:3]
	return render(request, 'poolServices/home.html', {'services':services,'reviews':reviews})

def services_page(request):
	services = MonthlyService.objects.all()
	return render(request, 'poolServices/services.html', {'services':services})

def createReview(request):
	if request.method == "GET":
		return render(request,'poolServices/createReview.html', {'form':ReviewForm()})
	else:
		form = ReviewForm(request.POST)
		newReview = form.save()
		return redirect('createReview')

def review_page(request):
	reviews = review.objects.all()
	return render(request, 'poolServices/reviews.html', {'reviews':reviews})

clients/templates/clients/new_client.html
<!DOCTYPE html>
<html>
{% extends "poolServices/base.html" %}
{% load static %}
<body>
{% block content %}

<br>
<br>
<br>
<br>
<br>

<div class="container-fluid text-center" style="background-color: #f1f1f1;">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
     
    </div>
 
    <div class="col-sm-8 text-center"> 
       <br> 
        <div class="row content">

        <div class="col-sm-6 text-center"> 
                        <h2>Rocky Powell</h2>
              <h2>(281) 620-1524</h2>
            </div>
        <div class="col-sm-6 text-center"> 
                        <h2>Gus Powell</h2>
              <h2>(832) 499-2139</h2>
            </div>

  
 

        </div>
			             <h1>Contact Us</h1>
              <p>Have any questions? Ready to push you pool problems away? Leave some information for us and we'll reach out to discuss how we can help!</p>

			<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Submit</button>
			</form>

        <br>
  
    </div>
    <div class="col-sm-2 sidenav">

  
    </div>
  </div>
</div>




{% endblock %}
</body>

</html>

clients/templates/clients/repair_form.html
<!DOCTYPE html>
<html>
{% extends "poolServices/base.html" %}
{% load static %}
<body>
{% block content %}

<br>
<br>
<br>
<br>
<br>

<div class="container-fluid text-center" style="background-color: #f1f1f1;">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
     
    </div>
 
    <div class="col-sm-8 text-center"> 
			  <h1>Need A Repair??</h1>
              <p>Give us an idea of any problems you know of that are going on! We'll reach out to you (via phone call) to discuss what we can do!</p>


			<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Submit</button>
			</form>
  <br>
    </div>
    <div class="col-sm-2 sidenav">

  
    </div>
  </div>
</div>




{% endblock %}
</body>

</html>

poolServices/templates/poolServices/base.html
<!DOCTYPE html>

<html lang="en">
  {% load static %}
<head>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Francois+One&display=swap" rel="stylesheet">


  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {
      height: auto
    }
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-image: url('{% static 'poolServices/concrete.jpg' %}');
      height: auto;
    }


    h1 {

      font-size: 95;
      color: #0104d8;
      font-weight: 700;
      font-family: 'Francois One', sans-serif;
  
    }
    h2 {

      font-size: 32;
      color: black;
      font-family: "Impact", Charcoal, sans-serif;
  
    }

    h3 {
      font-size: 28;
      color: #0104d8;
      font-family: 'Architects Daughter', cursive;
    }


    p {
      font-family: 'Francois One', sans-serif;
      font-size: 28;
      color: #0104d8;
      
      
    }

  p.reviews {
    font-size: 42;
    color: #0104d8;
  }

  b {

    font-weight: 700;
    font-size: 32;
  }

  b.red {
    color: red;
    font-weight: 100;
    font-size: 32;
  }

  b.green {
    color: green;
    font-weight: 50;
    font-size: 32;
  }


    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    body {
  background-image: url('{% static 'poolServices/bluePool.jpg' %}');
  background-repeat: no-repeat;
  background-attachment: fixed;  
  background-size: cover;
}
  </style>
<title>Rocky's Pool Cleaning</title>

</head>


<body>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger text-center text-white" href="{% url 'home' %}"><h1 style="color: white; font-size: 24;">Rocky's<br>Pool Care</h1></a>
                  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold text-white rounded" style="background-color: #0104d8;" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-white" href="{% url 'home' %}"><p style="color: white; font-size: 20;">Home</p></a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-white" href="{% url 'services' %}"><p style="color: white; font-size: 20;">Pool Care</p></a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-white" href="{% url 'clients:repair' %}"><p style="color: white; font-size: 20;">Repairs</p></a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-white" href="{% url 'clients:clients' %}"><p style="color: white; font-size: 20;">Contact</p></a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>




      <br>
      <br>


   










   <div class="container">
  {% block content %}
      {% endblock %}

    </div>

   <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>






</html>

poolServices/templates/poolServices/createReview.html
<!DOCTYPE html>
<html>
{% extends "poolServices/base.html" %}
{% load static %}
<body>
{% block content %}

<br>
<br>
<br>
<br>
<br>

<div class="container-fluid text-center" style="background-color: #f1f1f1;">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
     
    </div>

    <div class="col-sm-8 text-center"> 
			  <h1>Leave a Review</h1>


			<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Create</button>
			</form>
  
    </div>
    <div class="col-sm-2 sidenav">

  
    </div>
  </div>
</div>




{% endblock %}
</body>

</html>

poolServices/templates/poolServices/home.html
<html>

{% extends "poolServices/base.html" %}
{% load static %}
{% block content %}
<body>

<br>
<br>


<div class="container-fluid text-center" style="background-color: #333232">    
  <div class="row content">
    <div class="col-md-2 sidenav">
      <div class='row content'>
        <br>
        <br>
      </div>
    </div>
    <div class="col-md-8 text-center" style="background-color: #fff;">
           <div class="row content">
            <div class="col-12" style="background-color: #f1f1f1;" >
              <br>
          
            </div>
           </div>
     <br>
     <br>

           <div class="row content">
            <div class="col-12" style="background-color: #fff;" >
              <br>
                    <h1 style="size: 30;">ROCKY's</h1>
            </div>
           </div>
      <h1>Pool Care</h1>
      <br>
      <br>
      <img src="{% static 'poolServices/poolhomepage.jpg' %}" class="img-fluid">

      <br>
      <br>

      <p><b>Rocky's Pool Care </b>clears up the problems with <b>pools.</b> As a family owned and operated service for over <b> 20 years </b>, we know our way around a <b>pool...</b> Push your problems to us, we'll handle your<b> pool </b>care with<b> weekly </b> visits for a flat monthly price! Rocky's Pool Care makes for a <b>perfect</b> pool!</p> 
      <br>
      <h2>Free Phone Consultations</h2>
      <p>* Cypress * Jersey Village * Spring * Tomball * Waller *</p>
      <a class="btn btn-primary btn-sm" style="color: #0104d8;" href="{% url 'clients:clients' %}" role="button"><h1 style="font-size: 18; color: white;">Get Quote</h1></a>

      <hr>

       <br> 
      <div class="row content">

        <div class="col-sm-6 text-center"> 
                        <h2>Rocky Powell</h2>
              <h2>(281) 620-1524</h2>
            </div>
        <div class="col-sm-6 text-center"> 
                        <h2>Gus Powell</h2>
              <h2>(832) 499-2139</h2>
            </div>

       

  
    </div>
 <br>
       <div class="row content text-center">
        <div class="col-12" style="background-color: #333232" >
          <br>
          <h1 style="color: white; font-size: 32;">Reviews</h1>
          {% for review in reviews %}

          <div class="col-sm-12 text-center">

            <p style="color: white; font-size: 20">"{{ review.comments }}"</p>
           
            <p style="color: white; font-size: 14">-{{ review.name }}, {{ review.location }}</p>

          </div>


          {% endfor %}
          
          
          <div class="col-sm-12 text-center">

          <a class="btn btn-sm" style="color: #fff;" href="{% url 'reviews' %}" role="button"><h1 style="font-size: 14; color: white;">VIEW ALL</h1></a>

              </div>
             <br> 
             <br>
        </div>
        
       </div>

       <br>

      <h2 style="text-decoration: underline wavy blue;">Care Includes:</h2>

      <br>

      <div class='row content'>

{% for service in services %}

 <div class="col-sm-4 text-center" style="background-color: #fff;">
      <p style="font-size: 22;">{{ service.title }}</p>
    </div>

{% endfor %}
</div>


<a class="btn btn-primary btn-sm" style="color: #fff;" href="{% url 'services' %}" role="button">Learn More</a>



<br>
<br>
    </div>


    <div class="col-md-2 sidenav">
      <div class='row content'></div>
    </div>
  </div>


</div>




<footer class="container-fluid text-center ">
<p style="font-size: 12; color: white;">Website Made By DeeLeeTech</p>
</footer>

{% endblock %}


</body>






</html>

poolServices/templates/poolServices/reviews.html
<!DOCTYPE html>
<html>
{% extends "poolServices/base.html" %}
{% load static %}


<body>
{% block content %}

<div class="container-fluid text-center" style="background-color: #f1f1f1;">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
     
    </div>
  
    <div class="col-sm-8 text-center" style="background-color: #fff"> 
		<br>
		<br>
	   	<br>
        <br>
          <h1 style="color: #0104d8; font-size: 48;">Reviews</h1>

          <br>
          <br>
          <div class="row content">
          	<br>
	          {% for review in reviews %}
				
	          <div class="col-sm-12 text-center" style="background-color: #f1f1f1;">

	          	<br>


	            <h3>"{{ review.comments }}"</h3>
	           
	            <h3>-{{ review.name }}, {{ review.location }}</h3>
				<br>
	          </div>
	          <br>
	          <br>
	          {% endfor %}
     	 </div>


  
    </div>
    <div class="col-sm-2 sidenav">

  
    </div>
  </div>
</div>














{% endblock %}

</body>
</html>

poolServices/templates/poolServices/services.html
<html>

{% extends "poolServices/base.html" %}
{% load static %}
{% block content %}
<body>

<br>
<br>


<div class="container-fluid text-center" style="background-color: #f1f1f1;">    
  <div class="row content">
    <div class="col-md-2 sidenav">
      <div class='row content'>
        
      </div>
    </div>
    <div class="col-md-8 text-center" style="background-color: #fff;">
     <br>
     <br>
     <h1 style="size: 30;">Our Pool Care</h1>
     <br>
     <p style="color: black;">We maintain the cleaning and chemical upkeeping of your pool, making sure it is the prettiest part of your backyard! Stop lifting fingers and start dipping toes... we'll take care of rest!! Read about how we do it bellow</p>

           <div class="row content">
	        	<div class="col-12" style="background-color: #333232">
	       		<br>
	       		<br>
	       		</div>
	       	</div>
  <br>





		{% for service in services %}



		<div class="row content">
	        	<div class="col-6" style="background-color: #f1f1f1;" >
	       		<br>
					<h2>{{ service.title }}</h2>

			      <p>
			      	{{ service.description }}
			      </p>

   				</div>

   				<div class="col-6" style="background-color:  #f1f1f1;" >
				
				<img src="{{ service.image.url }}" class="img-fluid" alt="">

   				</div>
	    </div>


			 
			    
			<br>
			
		{% endfor %}


           <div class="row content">
	        	<div class="col-12" style="background-color: #333232" >
	       		<br>
	       		<br>
	       		</div>
	       	</div>

       <div class="row content">
        <div class="col-12" style="background-color: #f1f1f1;" >
       <br>
       		<h1 style="font-size: 36;"> Request Contact Here! </h1>
       		<a class="btn btn-primary btn-sm" style="color: #fff;" href="{% url 'clients:clients' %}" role="button">Contact</a>
       	<br>
       	<br>
        </div>
       </div>

    


    </div>


    <div class="col-md-2 sidenav">
      <div class='row content'></div>
    </div>
  </div>


</div>




<footer class="container-fluid text-center ">
<p style="font-size: 12; color: white;">Website Made By DeeLeeTech</p>
</footer>

{% endblock %}






</body>
</html>